version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    links:
      - php
    depends_on:
      - php
  php:
    build: .
    volumes:
      - ./:/app
    ports:
      - "9051"
    command: php /app/server.php
